# Default Vocode configuration
ui:
  log_level: debug
tools:
  - name: vectorops_read_files
    auto_approve: true
  - name: vectorops_summarize_files
    auto_approve: true
  - name: vectorops_list_files
    auto_approve: true
  - name: vectorops_search
    auto_approve: true
workflows:
  architect:
    nodes:
      - name: prompt
        type: input
        message: Enter your request
        confirmation: auto
        hide_final_output: true
        outcomes:
          - name: done
      - $include:
          template: nodes/discovery.yaml
        function_tokens_pct: 25
        confirmation: auto
      - $include:
          template: nodes/architect.yaml
        function_tokens_pct: 25
        reset_policy: keep_state
      - $include:
          template: nodes/coder.yaml
      - $include:
          template: nodes/apply_patch.yaml
          confirmation: auto
      - name: finish
        type: noop
    edges:
      - prompt.done -> discovery
      - discovery.done -> architect
      - architect.done -> coder
      - coder.done -> apply
      - apply.success -> prompt
      - apply.fail -> coder:keep_state
  diff:
    nodes:
      - name: prompt
        type: input
        message: Enter your request
        confirmation: auto
        outcomes:
          - name: done
      - $include:
          template: nodes/architect.yaml
        model: gpt-5-mini
      - name: finish
        type: noop
    edges:
      - prompt.done -> architect
      - architect.done -> finish
  coder:
    nodes:
      - name: prompt
        type: input
        message: Enter your request
        confirmation: auto
        outcomes:
          - name: done
      - $include:
          template: nodes/coder.yaml
      - name: finish
        type: noop
    edges:
      - prompt.done -> coder
      - coder.done -> finish
  idler:
    nodes:
      - name: prompt
        type: input
        message: Enter your request
        confirmation: auto
        outcomes:
          - name: done
      - name: pause
        type: noop
        sleep_seconds: 15
        outcomes:
          - name: done
      - name: debug
        type: debug
        outcomes:
          - name: done
      - name: done
        type: noop
        confirmation: auto
    edges:
      - prompt.done -> pause
      - pause.done -> debug
      - debug.done -> done
