# Default Vocode configuration
workflows:
  architect:
    nodes:
      - name: prompt
        type: input
        message: Enter your request
        confirmation: auto
        outcomes:
          - name: done
      - $include:
          template: nodes/discovery.yaml
          function_tokens_pct: 25
      - $include:
          template: nodes/architect.yaml
          function_tokens_pct: 25
      - $include:
          template: nodes/coder.yaml
      - $include:
          template: nodes/apply_patch.yaml
          confirmation: auto
      - name: finish
        type: noop
    edges:
      - prompt.done -> discovery
      - discovery.done -> architect
      - architect.done -> coder
      - coder.done -> apply
      - apply.success -> finish
      - apply.fail -> coder:keep_state
  diff:
    nodes:
      - name: prompt
        type: input
        message: Enter your request
        confirmation: auto
        outcomes:
          - name: done
      - $include:
          template: nodes/architect.yaml
        model: gpt-4.1
      - name: finish
        type: noop
    edges:
      - prompt.done -> architect
      - architect.done -> finish
  coder:
    nodes:
      - name: prompt
        type: input
        message: Enter your request
        confirmation: auto
        outcomes:
          - name: done
      - $include:
          template: nodes/coder.yaml
      - name: finish
        type: noop
    edges:
      - prompt.done -> coder
      - coder.done -> finish
