# Default Vocode configuration
ui:
#  log_level: debug
variables:
#  LLM_DISCOVERY_MODEL: openai/gpt-5-mini
#  LLM_ARCHITECT_MODEL: openai/gpt-5
#  LLM_CODER_MODEL: openai/gpt-5-mini
  LLM_DISCOVERY_MODEL: gemini/gemini-2.5-flash
  LLM_ARCHITECT_MODEL: gemini/gemini-2.5-pro
  LLM_CODER_MODEL: gemini/gemini-2.5-flash
  LLM_DIFF_FORMAT: patch
tools:
  - name: vectorops_read_files
    auto_approve: true
  - name: vectorops_summarize_files
    auto_approve: true
  - name: vectorops_list_files
    auto_approve: true
  - name: vectorops_search
    auto_approve: true
workflows:
  # Agentic builder
  architect:
    nodes:
      - name: prompt
        type: input
        message: Enter your request
        confirmation: auto
        hide_final_output: true
        outcomes:
          - name: done
      - $include:
          template: nodes/discovery.yaml
        function_tokens_pct: 25
        confirmation: auto
      - $include:
          template: nodes/architect.yaml
        tools:
          - vectorops_summarize_files
          - vectorops_read_files
        preprocessors:
          - name: file_read
            paths:
              - AGENTS.md
        function_tokens_pct: 25
        reset_policy: keep_results
      - $include:
          template: nodes/coder.yaml
        tools:
          - vectorops_read_files
        confirmation: auto
      - $include:
          template: nodes/apply_patch.yaml
        confirmation: auto
    edges:
      - prompt.done -> discovery
      - discovery.done -> architect
      - architect.done -> coder
      - coder.done -> apply
      - apply.success -> prompt
      - apply.fail -> coder:keep_state
  # Aider-like explicit coder loop
  coder:
    nodes:
      - name: prompt
        type: input
        message: Enter your request
        confirmation: auto
        hide_final_output: true
        outcomes:
          - name: done
      - $include:
          template: nodes/file_state.yaml
          skip: true
      - $include:
          template: nodes/architect.yaml
          reset_policy: keep_state
        preprocessors:
          - name: file_state
            mode: user
          - name: file_read
            mode: user
            paths:
              - AGENTS.md
      - $include:
          template: nodes/coder.yaml
        confirmation: auto
      - $include:
          template: nodes/apply_patch.yaml
        confirmation: auto
    edges:
      - prompt.done -> architect
      - architect.done -> coder
      - coder.done -> apply
      - apply.success -> prompt
      - apply.fail -> coder:keep_state
